spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zjlooong/config-repo.git
          username: zjloong@qq.com
          password: zjl950221
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 暴露bus_refresh等所有接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
